# Generated by Django 4.1.1 on 2023-02-19 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250, verbose_name='Descripcion')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de actualizacion')),
            ],
            options={
                'verbose_name': 'Acerca de',
                'verbose_name_plural': 'Acerca de nosotros',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, verbose_name='key Link')),
                ('name', models.CharField(max_length=100, verbose_name='Red Social')),
                ('url', models.URLField(blank=True, max_length=350, null=True, verbose_name='Enlace')),
                ('icon', models.CharField(max_length=100, verbose_name='Icono')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de actualizacion')),
            ],
            options={
                'verbose_name': 'Red Social',
                'verbose_name_plural': 'Redes Sociales',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created'], 'verbose_name': 'Publicacion', 'verbose_name_plural': 'Publicaciones'},
        ),
    ]
